### ISSUE TITLE
Build badge link broken

### ISSUE THREAD

**Issue by AdrienCorenflos** [computorg/published-202402-elmasri-optimal#6]
Noticed this while reading:
The build, review, report links point to the "computo" org, not computorg.

![image](https://github.com/user-attachments/assets/9a6cc1e7-5750-4d06-964a-4c882103a829)

https://computo.sfds.asso.fr/published-202402-elmasri-optimal/

**Comment by pneuvial** [comment]
Thanks for reporting!
